---
version: "2.1"
services:
  webtop:
    build: .
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - SUBFOLDER=/ #optional
      - KEYBOARD=en-us-qwerty #optional
    volumes:
      - ./data:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    #devices:
      #- /dev/dri:/dev/dri #optional
    shm_size: "2gb" #optional
    restart: unless-stopped
